### ISSUE TITLE
Cannot replicate the layout of example 02-02 w/ latest version of Chrome

### ISSUE THREAD

**Issue by lozandier** [abookapart/css-grid-layout-code#3]
## The Problem

I can't seem to replicate the layout examples at the end of 02-02 using the latest version of Chrome with CSS Grid Module Layout enabled; even if I copy & paste the styles from the Github example, I can't seem to replicate the layout as portrayed by the figures in the PDF or Ebook
## Example Code of the Problem Being Replicated

A pen of my attempt can be found [here](http://codepen.io/lozandier/pen/8115fa83c06db6f88d231b18859e1888)
## Potential Hangups I'm confused by that lead to this problem being more of a misunderstanding on my part as a reader
- `repeat` in the brief isn't as eased into as the gridbyexample.com examples you made long ago seemingly; perhaps I lost track on what the expected output & spanning 
- A typo: I nullified that by just copying and pasting what you posted after my attempt that I was certain was the same code didn't generate the outcome I was expected; unsurprisingly, copying and pasting directly from your source outcome didn't lead to a different outcome. Using Vim binding in Codepen, perhaps I keep copying and pasting my own code (doubtful)

**Comment by rachelandrew** [comment]
This is something that has recently changed in the Chrome implementation, if you set a min-height of 1% on the boxes the images are contained. I've not been able to confirm whether this is correct behaviour or not, although it behaves somewhat similarly to Flexbox.

If I find out that this is correct behaviour then I'll update the examples to match.

**Comment by lozandier** [comment]
@rachelandrew Understood, thanks for the thorough response. `min-height: 1%` did indeed correct the layout to appear as expected.

**Comment by rachelandrew** [comment]
Just coming back to this, I don't think this is the behaviour I thought it was. In my example I have max-height set to 100% which is why it does not exhibit the behaviour. So that was the difference between my example and yours. Anyway, just wanted to tidy up the thread :)

**Comment by paulirish** [comment]
Cool cool. Kevin pointed me over here. 
I personally know jack about grid layout, so I won't be able to help telling if something is a bug or not. 
But y'all think there is a bug in Chrome's implementation, feel free to report it at crbug.com... then if you ping me/addy/jake/etc, we can cc in the right people.

**Comment by lozandier** [comment]
@paulirish Understood; it was a mistake on my part mentioning you & Addy about this knowing Manuel on behalf of Igalia works on the Grid implementation in Blink: When I think Chrome (Dev Tools), I think of you and Addy immediately out of habit.

**Comment by mrego** [comment]
Just trying to explain a little bit more how it works.
There's an issue with the image size regarding the cell size.
If the image is smaller than the cell, it's stretched to fill the whole cell.
However, if the image is bigger than the cell, it's not shrunk to fit. So we need "`max-width|height: 100%;`" to shrink the image.

You can check the different behaviors in the next jsbin (notice that there's a [bug in Chrome](https://code.google.com/p/chromium/issues/detail?id=575182) so the image in the first case is not stretched horizontally, in Firefox it works as expected):
http://jsbin.com/rotomidena/1/edit?html,css,output

This is pretty similar to the behavior in flexbox, if the image has "`flex-grow: 1;`" and "`flex-shrink: 0;`". You can check it here:
http://jsbin.com/pohidafalu/1/edit?html,css,output

**Comment by rachelandrew** [comment]
Hi all - not sure why you were all invoked :) Kevin just needed to add the max-height (I didn't help by conflating the issue with something I'd been discussing with someone else about an hour before I saw the issue).

I think this behaviour trips up a lot of people (in Flexbox too) as it happens, as developers don't expect to need to add max-height in the same way they do max-width.

**Comment by lozandier** [comment]
@rachelandrew Thanks for clarifying what I misunderstood and thanks @mrego for further explaining in impressive detail what I misunderstood about this aspect of the grid module layout.
