### ISSUE TITLE
Unable to reproduce the Boxy layout in Chapter 2

### ISSUE THREAD

**Issue by herrjosua** [abookapart/css-grid-layout-code#4]
## Issue
I'm having trouble getting my version of the Boxy layout from Chapter 2 to display like the image in **FIG 2.4** (see attached screenshot below). I have tried multiple browsers include the latest versions of Firefox (56.0), Chrome (61.0.3163.100), and Chrome Canary (63.0.3233.0). I have tried copying the copy from the Github repo and encounter the same issue. I'm using the images provided in the repo. I also tried to apply the _min-height_ fix recommended by [this issue](https://github.com/abookapart/css-grid-layout-code/issues/3).

## Screenshot of my issue
![screen shot 2017-10-05 at 09 08 15](https://user-images.githubusercontent.com/1341786/31228803-bd859114-a9ac-11e7-8752-940c4f0a9572.png)

**Comment by jhjeong314** [comment]
I had the same problem.  

Please try
  `width:` 100%; height: `100%;`
instead of 
  `max-width:` 100%; max-height: `100%;`

It worked for me.

**Comment by herrjosua** [comment]
@jhjeong314 Thanks, your suggestion worked like a charm.

**Comment by bochap** [comment]
@rachelandrew Will it be possible to fix the code in the repo. I would not mind submitting a PR for it
